- name: Create a MariaDB systemctl override folder
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/mariadb.service.d
    owner: root
    group: root

- name: Always restart MySQL when it crashes, tell oom-killer to back off
  ansible.builtin.copy:
    src: files/override.conf
    dest: /etc/systemd/system/mariadb.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: systemctl daemon-reload

- name: Set up READ-COMMITTED isolation level
  ansible.builtin.copy:
    src: files/mysqld.cnf
    dest: /etc/mysql/conf.d/mysqld.cnf
    owner: root
    group: root
    mode: '0644'
  notify: restart mysql

- name: Update timezone info
  tags: [ timezone-update ]
  apt:
    name: tzdata
    state: latest
    install_recommends: no
  register: timezone_info

- name: Move system timezone info into MariaDB
  tags: [ timezone-update ]
  shell: >
    mysql_tzinfo_to_sql /usr/share/zoneinfo \
      | grep -v "^Warning" \
      | mysql --database=mysql
  when: timezone_info.changed
